# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "estoque-auto-backend"

[api]
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API endpoints.
# public and storage are always included.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# The maximum number of rows returned from a table or view. Limits payload size for accidental or malicious requests.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# Port used by db diff command to initialize the shadow database.
shadow_port = 54320
# The database major version to use. This has to be the same as your remote database's. Run `SHOW server_version;` on the remote database to check.
major_version = 15

[db.pooler]
# Port to use for the local connection pooler.
port = 54329
# Specifies when a server connection can be reused by other clients.
# Configure one of the supported pooler modes: `transaction`, `session`.
pool_mode = "transaction"
# How many server connections to allow per user/database pair.
default_pool_size = 15
# Maximum number of client connections allowed.
max_client_conn = 100

[realtime]
# Bind realtime via either IPv4 or IPv6. (default: IPv4)
# ip_version = "IPv4"

[studio]
# Port to use for Supabase Studio.
port = 54323
# External URL of the API server that frontend connects to.
api_url = "http://localhost:54321"

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
# Port to use for the email testing server web interface.
port = 54324
# Uncomment to expose additional ports for testing user applications that send emails.
# smtp_port = 2500
# pop3_port = 1100

[storage]
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604800 (1 week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = true
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
# Requires enable_refresh_token_rotation = true.
refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

# Uncomment to customize email template
# [auth.email.template.invite]
# subject = "You have been invited"
# content_path = "./supabase/templates/invite.html"

[auth.sms]
# Allow/disallow new user signups via SMS to your project.
enable_signup = true
# If enabled, users need to confirm their phone number before signing in.
enable_confirmations = false
# Template for sending a confirmation message when a user signs up with a phone number.
template = "Your code is {{ .Code }}"

[auth.external.apple]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[auth.external.azure]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[auth.external.bitbucket]
enabled = false
client_id = ""
secret = ""

[auth.external.discord]
enabled = false
client_id = ""
secret = ""

[auth.external.facebook]
enabled = false
client_id = ""
secret = ""

[auth.external.github]
enabled = false
client_id = ""
secret = ""

[auth.external.gitlab]
enabled = false
client_id = ""
secret = ""

[auth.external.google]
enabled = false
client_id = ""
secret = ""

[auth.external.keycloak]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[auth.external.linkedin]
enabled = false
client_id = ""
secret = ""

[auth.external.notion]
enabled = false
client_id = ""
secret = ""

[auth.external.slack]
enabled = false
client_id = ""
secret = ""

[auth.external.spotify]
enabled = false
client_id = ""
secret = ""

[auth.external.twitch]
enabled = false
client_id = ""
secret = ""

[auth.external.twitter]
enabled = false
client_id = ""
secret = ""

[auth.external.workos]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[auth.external.zoom]
enabled = false
client_id = ""
secret = ""

# Use pre-defined map of JWT claims to database columns/expressions. The key is the JWT claim path, the value is the database column/expression.
# [auth.jwt_map]
# sub = "users.id"
# email = "users.email"
# email_verified = "users.email_verified"
# phone_verified = "users.phone_verified"
# name = "users.full_name"
# given_name = "users.first_name"
# family_name = "users.last_name"
# picture = "users.avatar_url"
# company = "users.company"
# role = "users.role"

# Configure one of the supported SMS providers: `twilio`, `messagebird`, `textlocal`, `vonage`.
[auth.sms.twilio]
enabled = false
# Find these values in your Twilio Console.
account_sid = ""
# This is the "Auth Token" in your Twilio Console.
message_service_sid = ""
# This is the "Messaging Service SID" in your Twilio Console.
# message_service_sid = ""

[auth.sms.messagebird]
enabled = false
# Find this value in your MessageBird Console.
access_key = ""

[auth.sms.textlocal]
enabled = false
# Find this value in your TextLocal Console.
api_key = ""

[auth.sms.vonage]
enabled = false
# Find these values in your Vonage Console.
api_key = ""
api_secret = ""

# Configure one of the supported MFA factors: `totp`, `webauthn`.
# [auth.mfa.totp]
# enabled = false
# # The issuer name to be used in the TOTP QR code.
# issuer = ""

# [auth.mfa.webauthn]
# enabled = false
# # The relying party name to be used in the WebAuthn flow.
# rp_name = ""

# Use an external OAuth provider. The full list of providers are: `apple`, `azure`, `bitbucket`,
# `discord`, `facebook`, `github`, `gitlab`, `google`, `keycloak`, `linkedin`, `notion`, `slack`,
# `spotify`, `twitch`, `twitter`, `workos`, `zoom`.
# [auth.external.apple]
# enabled = true
# client_id = "your-client-id"
# secret = "your-client-secret"
# # Overrides the default auth redirectUrl.
# redirect_uri = ""
# # Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
# url = ""

[functions]
# Configure one of the supported import map providers: `import_map`, `bundle`.
import_map_provider = "import_map"
# The import map file to use when the import map provider is set to `import_map`.
import_map_path = "./import_map.json"
# The bundle file to use when the import map provider is set to `bundle`.
# bundle_path = "./edge-functions-bundle.js"

# [analytics]
# enabled = false
# port = 54327
# vector_port = 54328
# # Configure one of the supported backends: `postgres`, `bigquery`.
# backend = "postgres"
# # Configure one of the supported sample rates: `0.1`, `0.01`, `0.001`.
# sample_rate = 0.1
# # Configure one of the supported log levels: `debug`, `info`, `warn`, `error`.
# log_level = "info"

# [experimental]
# # Enable the new auth UI
# enable_auth_ui = false 