name: Deploy to Supabase

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      #- name: Run tests
      #  run: npm test
      #  env:
     #     SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
     #     SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
     #     SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

      #- name: Lint code
      #  run: npm run lint

      - name: Build project
        run: npm run build

      - name: Deploy to Supabase (Production)
        if: github.ref == 'refs/heads/main'
        run: |
          supabase functions deploy --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
      #    supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
      #    supabase db push
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      #- name: Deploy to Supabase (Staging)
      #  if: github.ref == 'refs/heads/develop'
      #  run: |
      #    supabase link --project-ref ${{ secrets.SUPABASE_STAGING_PROJECT_REF }}
      #    supabase db push
      #    supabase functions deploy --project-ref ${{ secrets.SUPABASE_STAGING_PROJECT_REF }}
      #  env:
      #    SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Run database migrations
        if: github.ref == 'refs/heads/main'
        run: |
          yes | supabase db reset --db-url "postgresql://postgres.${{ secrets.SUPABASE_PROJECT_REF }}:${{ secrets.SUPABASE_DB_PASSWORD }}@aws-0-us-east-1.pooler.supabase.com:5432/postgres"
      #    supabase db push --db-url "postgresql://postgres.${{ secrets.SUPABASE_PROJECT_REF }}:${{ secrets.SUPABASE_DB_PASSWORD }}@aws-0-us-east-1.pooler.supabase.com:5432/postgres" --debug
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}

      - name: Seed database
        if: github.ref == 'refs/heads/main'
        run: |
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
          supabase db reset --linked --seed
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}